# Generated by Django 4.0.5 on 2022-06-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='id_usuario',
            new_name='nombre_usuario',
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='id_libro',
            new_name='titulo',
        ),
    ]
