# Generated by Django 4.0.5 on 2022-06-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0002_rename_id_usuario_prestamo_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=101),
        ),
    ]
